<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <!-- Versionamento -->
        <PackageReference Include="Asp.Versioning.Http" Version="8.1.0" />
        <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />

        <!-- HealthChecks -->
        <PackageReference Include="AspNetCore.HealthChecks.MongoDb" Version="9.0.0" />
        <PackageReference Include="AspNetCore.HealthChecks.Oracle" Version="9.0.0" />
        <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
        <PackageReference Include="AspNetCore.HealthChecks.Uris" Version="9.0.0" />

        <!-- Entity Framework / Oracle -->
        <PackageReference Include="EntityFramework" Version="6.5.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="MongoDB.Bson" Version="3.5.0" />
        <PackageReference Include="MongoDB.Driver" Version="3.5.0" />
        <PackageReference Include="MongoDB.Driver.Core" Version="3.5.0" />
        <PackageReference Include="Oracle.EntityFrameworkCore" Version="9.23.90" />
        <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.0" />

        <!-- MongoDB (força as libs 3.0.0 em TODAS as dependências) -->

        <!-- JWT / Auth -->
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
        <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.14.0" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />

        <!-- Health & Swagger -->
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="9.0.10" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
        <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="7.0.6" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\VisionHive.Application\VisionHive.Application.csproj" />
      <ProjectReference Include="..\VisionHive.Infrastructure\VisionHive.Infrastructure.csproj" />
        <ProjectReference Include="..\VisionHive.Domain\VisionHive.Domain.csproj" />
    </ItemGroup>

</Project>
