<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="EntityFramework" Version="6.5.1" />
      <PackageReference Include="FluentValidation" Version="12.0.0" />
      <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.8" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.OpenApi" Version="1.6.25" />
      <PackageReference Include="MongoDB.Driver" Version="3.5.0" />
      <PackageReference Include="Oracle.EntityFrameworkCore" Version="9.23.90" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.Text.Json" Version="9.0.10" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\VisionHive.Domain\VisionHive.Domain.csproj" />
        <ProjectReference Include="..\VisionHive.Infrastructure\VisionHive.Infrastructure.csproj" />
    </ItemGroup>

</Project>
